spring.datasource.url=jdbc:mysql://mysql:3306/db_repositoriooym?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=America/Mexico_City
spring.datasource.username=root
spring.datasource.password=Qazwsx12#$
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.hibernate.SQL=warn

#Peticion y maximo de archivo a subir
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=3584MB
server.tomcat.connection-timeout=600000
server.tomcat.max-swallow-size=1048576000

#Puerto y url del front
server.port=8080
app.frontend.url=http://10.119.79.95