spring.datasource.url=jdbc:mysql://localhost/db_repositoriooym?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=01052012Mark
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
spring.jpa.hibernate.ddl-auto=create
logging.level.org.hibernate.SQL=debug

#Peticion y maximo de archivo a subir
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB

#Ubicacion de los archivos
folder.location=documentacion_proyectos

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.serialization.write-dates-as-timestamps=false

#Puerto y url del front
server.port=8080
app.frontend.url=http://localhost:8083